import Footer from "../Footer/Footer";
import Header from "../Header/Header";
import React from "react";
import {createTheme, ThemeProvider} from "@mui/material/styles";
import {Container, CssBaseline} from "@mui/material";
import Head from 'next/head'

type Props = {
    children?: React.ReactNode;
    home?: boolean;
};

const theme = createTheme();

const DefaultLayout = ({children}: Props) => {
    return (
        <>
            <ThemeProvider theme={theme}>
                <CssBaseline />

                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>


                <Header />
                <Container component="main" maxWidth="sm">
                    {children}
                </Container>
                <Footer />
            </ThemeProvider>
        </>
    )
};

export default DefaultLayout;
